/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Collections;
import java.util.Comparator;
import java.util.LinkedList;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.TipoTransacao;
import model.ControleSaldo;
import model.Despesa;
import model.ManipuladorArquivo;
import model.Receita;
import model.CategoriaTransacao;
import model.Transacao;

/**
 *
 * @author crist
 */
public class App extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public App() {
        initComponents();
    }
    
    private static boolean validarValorValido(String valorStr) {
        try {
            
            var valorConvertido = Double.valueOf(valorStr);
            if (valorConvertido <= 0)
                return false;
            return true;
        } catch (NumberFormatException e) {
            return false;
        }
    }
    
    private static boolean validarDataValida(String dataStr) {
        String regex = "^(0[1-9]|[12][0-9]|3[01])/(0[1-9]|1[0-2])/\\d{4}$";
        Pattern pattern = Pattern.compile(regex);
        Matcher matcher = pattern.matcher(dataStr);

        return matcher.matches();
    }
    
    private static LocalDate transformarStringData(String dataStr) {
        DateTimeFormatter formato = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        LocalDate data;
        data = LocalDate.parse(dataStr, formato);
        
        return data;
    }
    
    private boolean cadastrarTransacao(String valorFormatado, String dataTransacao, String descricaoTipo, CategoriaTransacao tipoTransacao) {
        var informacoesInvalidas = false;
        if (valorFormatado.isBlank()) {
            JOptionPane.showMessageDialog(rootPane, "É necessário informar um valor para cadastrar a transação!", "Aviso", JOptionPane.WARNING_MESSAGE);
            informacoesInvalidas = true;
        }
        if (dataTransacao.isBlank()) {
            JOptionPane.showMessageDialog(rootPane, "É necessário informar uma data para cadastrar a transação!", "Aviso", JOptionPane.WARNING_MESSAGE);
            informacoesInvalidas = true;
        }
        if (informacoesInvalidas) {
            return false;
        }
        if (!validarValorValido(valorFormatado)) {
            JOptionPane.showMessageDialog(rootPane, "O valor está em um formato inválido!", "Erro", JOptionPane.ERROR_MESSAGE);
            informacoesInvalidas = true;
        }
        if (!validarDataValida(dataTransacao)) {
            JOptionPane.showMessageDialog(rootPane, "A data está em um formato inválido!", "Erro", JOptionPane.ERROR_MESSAGE);
            informacoesInvalidas = true;
        }
        if (informacoesInvalidas) {
            return false;
        }
        
        var data = transformarStringData(dataTransacao);
        var categoria = TipoTransacao.getTipoTransacaoPorDescricao(descricaoTipo);
        Transacao transacao;
        
        if (tipoTransacao == CategoriaTransacao.DESPESA) {
            transacao = new Despesa(Double.parseDouble(valorFormatado), categoria, data);
        } else {
            transacao = new Receita(Double.parseDouble(valorFormatado), categoria, data);
        }

        // salvar no arquivo        
        try {
            ManipuladorArquivo.incluirTransacao(transacao);
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        
        return true;
    }
        
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelIncluirDespesa = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tfValorDaDespesa = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cbTipoDeDespesa = new javax.swing.JComboBox<>();
        btIncluirDespesa = new javax.swing.JButton();
        lblDataDespesa = new javax.swing.JLabel();
        tfDataDespesa = new javax.swing.JTextField();
        PanelIncluirReceita = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        tfValorDaReceita = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cbTipoDeReceita = new javax.swing.JComboBox<>();
        btIncluirReceita = new javax.swing.JButton();
        lblDataReceita = new javax.swing.JLabel();
        tfDataReceita = new javax.swing.JTextField();
        PanelConsultaDeSaldo = new javax.swing.JPanel();
        btConsultarSaldoAtual = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btConsultarSaldoIndependenteDaData = new javax.swing.JButton();
        lbConsultaSaldoDataAtual = new javax.swing.JLabel();
        lbConsultaSaldoIndependenteDoPeriodo = new javax.swing.JLabel();
        PanelConsultaReceita = new javax.swing.JPanel();
        btConsultarReceitas = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbConsultarReceita = new javax.swing.JTable();
        PanelConsultaDespesa = new javax.swing.JPanel();
        cbTipoDeDespesaConsulta = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        btConsultarDespesas = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbConsultarDespesaFiltrada = new javax.swing.JTable();
        PanelConsultarLancamentos = new javax.swing.JPanel();
        btConsultarLancamentos = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbConsultarLancamentos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelIncluirDespesa.setBorder(javax.swing.BorderFactory.createTitledBorder("Incluir Despesa"));

        jLabel2.setText("Valor da Despesa: ");

        jLabel3.setText("Tipo da Despesa");

        cbTipoDeDespesa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alimentação", "Transporte", "Residência", "Saúde", "Educação", "Entretenimento", "Outras" }));

        btIncluirDespesa.setText("Incluir Despesa");
        btIncluirDespesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIncluirDespesaActionPerformed(evt);
            }
        });

        lblDataDespesa.setText("Data da Despesa: ");

        tfDataDespesa.setToolTipText("Data no formato dia/mês/ano");

        javax.swing.GroupLayout PanelIncluirDespesaLayout = new javax.swing.GroupLayout(PanelIncluirDespesa);
        PanelIncluirDespesa.setLayout(PanelIncluirDespesaLayout);
        PanelIncluirDespesaLayout.setHorizontalGroup(
            PanelIncluirDespesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelIncluirDespesaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelIncluirDespesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDataDespesa)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addGap(10, 10, 10)
                .addGroup(PanelIncluirDespesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelIncluirDespesaLayout.createSequentialGroup()
                        .addComponent(btIncluirDespesa)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(cbTipoDeDespesa, 0, 197, Short.MAX_VALUE)
                    .addComponent(tfValorDaDespesa)
                    .addComponent(tfDataDespesa, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        PanelIncluirDespesaLayout.setVerticalGroup(
            PanelIncluirDespesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelIncluirDespesaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelIncluirDespesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfValorDaDespesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelIncluirDespesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDataDespesa)
                    .addComponent(tfDataDespesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelIncluirDespesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbTipoDeDespesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btIncluirDespesa)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        PanelIncluirReceita.setBorder(javax.swing.BorderFactory.createTitledBorder("Incluir Receita"));

        jLabel4.setText("Valor da Receita");

        jLabel5.setText("Tipo de Receita:");

        cbTipoDeReceita.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Recebimento de Salário", "Décimo Terceiro", "Férias", "Outras" }));
        cbTipoDeReceita.setToolTipText("");

        btIncluirReceita.setText("Incluir Receita");
        btIncluirReceita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIncluirReceitaActionPerformed(evt);
            }
        });

        lblDataReceita.setText("Data da Receita: ");

        tfDataReceita.setToolTipText("Data no formato dia/mês/ano");

        javax.swing.GroupLayout PanelIncluirReceitaLayout = new javax.swing.GroupLayout(PanelIncluirReceita);
        PanelIncluirReceita.setLayout(PanelIncluirReceitaLayout);
        PanelIncluirReceitaLayout.setHorizontalGroup(
            PanelIncluirReceitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelIncluirReceitaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelIncluirReceitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(lblDataReceita)
                    .addComponent(jLabel5))
                .addGap(16, 16, 16)
                .addGroup(PanelIncluirReceitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btIncluirReceita)
                    .addGroup(PanelIncluirReceitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(tfDataReceita, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                        .addComponent(tfValorDaReceita, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                        .addComponent(cbTipoDeReceita, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        PanelIncluirReceitaLayout.setVerticalGroup(
            PanelIncluirReceitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelIncluirReceitaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelIncluirReceitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfValorDaReceita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelIncluirReceitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDataReceita)
                    .addComponent(tfDataReceita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelIncluirReceitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbTipoDeReceita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btIncluirReceita)
                .addContainerGap())
        );

        PanelConsultaDeSaldo.setBorder(javax.swing.BorderFactory.createTitledBorder("Consulta de Saldo"));

        btConsultarSaldoAtual.setText("Consultar");
        btConsultarSaldoAtual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultarSaldoAtualActionPerformed(evt);
            }
        });

        jLabel1.setText("Consultar saldo até a data atual:");

        jLabel6.setText("Consultar saldo independente do período:");

        btConsultarSaldoIndependenteDaData.setText("Consultar");
        btConsultarSaldoIndependenteDaData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultarSaldoIndependenteDaDataActionPerformed(evt);
            }
        });

        lbConsultaSaldoDataAtual.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbConsultaSaldoIndependenteDoPeriodo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout PanelConsultaDeSaldoLayout = new javax.swing.GroupLayout(PanelConsultaDeSaldo);
        PanelConsultaDeSaldo.setLayout(PanelConsultaDeSaldoLayout);
        PanelConsultaDeSaldoLayout.setHorizontalGroup(
            PanelConsultaDeSaldoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelConsultaDeSaldoLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(PanelConsultaDeSaldoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelConsultaDeSaldoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbConsultaSaldoDataAtual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbConsultaSaldoIndependenteDoPeriodo, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelConsultaDeSaldoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btConsultarSaldoIndependenteDaData, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btConsultarSaldoAtual, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        PanelConsultaDeSaldoLayout.setVerticalGroup(
            PanelConsultaDeSaldoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelConsultaDeSaldoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelConsultaDeSaldoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbConsultaSaldoDataAtual, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(PanelConsultaDeSaldoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(btConsultarSaldoAtual)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelConsultaDeSaldoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(PanelConsultaDeSaldoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btConsultarSaldoIndependenteDaData))
                    .addComponent(lbConsultaSaldoIndependenteDoPeriodo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        PanelConsultaReceita.setBorder(javax.swing.BorderFactory.createTitledBorder("Consulta de Receitas"));

        btConsultarReceitas.setText("Consultar Receitas");
        btConsultarReceitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultarReceitasActionPerformed(evt);
            }
        });

        tbConsultarReceita.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Data", "Tipo Transação", "Valor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tbConsultarReceita);

        javax.swing.GroupLayout PanelConsultaReceitaLayout = new javax.swing.GroupLayout(PanelConsultaReceita);
        PanelConsultaReceita.setLayout(PanelConsultaReceitaLayout);
        PanelConsultaReceitaLayout.setHorizontalGroup(
            PanelConsultaReceitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelConsultaReceitaLayout.createSequentialGroup()
                .addGroup(PanelConsultaReceitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelConsultaReceitaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelConsultaReceitaLayout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(btConsultarReceitas)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelConsultaReceitaLayout.setVerticalGroup(
            PanelConsultaReceitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelConsultaReceitaLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(btConsultarReceitas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        PanelConsultaDespesa.setBorder(javax.swing.BorderFactory.createTitledBorder("Consulta de Despesa"));

        cbTipoDeDespesaConsulta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Alimentação", "Transporte", "Residência", "Saúde", "Educação", "Entretenimento", "Outras Despesas" }));
        cbTipoDeDespesaConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTipoDeDespesaConsultaActionPerformed(evt);
            }
        });

        jLabel8.setText("Tipo de despesa:");

        btConsultarDespesas.setText("Consultar Despesas");
        btConsultarDespesas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultarDespesasActionPerformed(evt);
            }
        });

        tbConsultarDespesaFiltrada.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Data", "Tipo Transação", "Valor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tbConsultarDespesaFiltrada);

        javax.swing.GroupLayout PanelConsultaDespesaLayout = new javax.swing.GroupLayout(PanelConsultaDespesa);
        PanelConsultaDespesa.setLayout(PanelConsultaDespesaLayout);
        PanelConsultaDespesaLayout.setHorizontalGroup(
            PanelConsultaDespesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelConsultaDespesaLayout.createSequentialGroup()
                .addGroup(PanelConsultaDespesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelConsultaDespesaLayout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PanelConsultaDespesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btConsultarDespesas, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                            .addComponent(cbTipoDeDespesaConsulta, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(PanelConsultaDespesaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(9, Short.MAX_VALUE))
        );
        PanelConsultaDespesaLayout.setVerticalGroup(
            PanelConsultaDespesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelConsultaDespesaLayout.createSequentialGroup()
                .addGroup(PanelConsultaDespesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cbTipoDeDespesaConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btConsultarDespesas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PanelConsultarLancamentos.setBorder(javax.swing.BorderFactory.createTitledBorder("Consulta de Lançamentos"));

        btConsultarLancamentos.setText("Consultar Lançamentos");
        btConsultarLancamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultarLancamentosActionPerformed(evt);
            }
        });

        tbConsultarLancamentos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Data", "Categoria", "Tipo Transação", "Valor", "Saldo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tbConsultarLancamentos);

        javax.swing.GroupLayout PanelConsultarLancamentosLayout = new javax.swing.GroupLayout(PanelConsultarLancamentos);
        PanelConsultarLancamentos.setLayout(PanelConsultarLancamentosLayout);
        PanelConsultarLancamentosLayout.setHorizontalGroup(
            PanelConsultarLancamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelConsultarLancamentosLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(btConsultarLancamentos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelConsultarLancamentosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        PanelConsultarLancamentosLayout.setVerticalGroup(
            PanelConsultarLancamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelConsultarLancamentosLayout.createSequentialGroup()
                .addComponent(btConsultarLancamentos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelConsultaReceita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PanelIncluirReceita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelIncluirDespesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PanelConsultaDespesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PanelConsultaDeSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PanelConsultarLancamentos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(24, 24, 24))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PanelIncluirReceita, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PanelIncluirDespesa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PanelConsultaDespesa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PanelConsultaReceita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(PanelConsultarLancamentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelConsultaDeSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btConsultarSaldoAtualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultarSaldoAtualActionPerformed
        try {
            Double saldo = ControleSaldo.calcularSaldoAteDataAtual();
            lbConsultaSaldoDataAtual.setText(String.format("R$ %.2f", saldo));
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btConsultarSaldoAtualActionPerformed

    private void btConsultarReceitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultarReceitasActionPerformed
        LinkedList<Transacao> receitas;
        try {
            receitas = ControleSaldo.retornaTransacoesDeReceita();
        }
        catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }
        DefaultTableModel modelo = (DefaultTableModel) tbConsultarReceita.getModel();
        modelo.setRowCount(0);
        var modeloColuna = tbConsultarReceita.getColumnModel();
        modeloColuna.getColumn(0).setPreferredWidth(25);
        modeloColuna.getColumn(1).setPreferredWidth(100);
        modeloColuna.getColumn(2).setPreferredWidth(35);
        for (var receita : receitas) {
            modelo.addRow(new Object[]{receita.getData().format(DateTimeFormatter.ofPattern("dd/MM/yyyy")),
                                        receita.getTipoTransacao().getDescricao(),
                                        String.format("R$ %.2f", receita.getValor())});
        }
    }//GEN-LAST:event_btConsultarReceitasActionPerformed

    private void cbTipoDeDespesaConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTipoDeDespesaConsultaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTipoDeDespesaConsultaActionPerformed

    private void btConsultarDespesasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultarDespesasActionPerformed
        LinkedList<Transacao> despesas;
        try {
            var tipo = TipoTransacao.getTipoTransacaoPorDescricao(cbTipoDeDespesaConsulta.getSelectedItem().toString());
            despesas = ControleSaldo.retornaTransacoesDeDespesa(tipo);
        }
        catch (IllegalArgumentException e) {
            try {
                despesas = ControleSaldo.retornaTransacoesDeDespesa(null);
            } catch (IllegalArgumentException ex) {
                JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
                return;
            }
        }
        
        DefaultTableModel modelo = (DefaultTableModel) tbConsultarDespesaFiltrada.getModel();
        modelo.setRowCount(0);
        var modeloColuna = tbConsultarDespesaFiltrada.getColumnModel();
        modeloColuna.getColumn(0).setPreferredWidth(25);
        modeloColuna.getColumn(1).setPreferredWidth(100);
        modeloColuna.getColumn(2).setPreferredWidth(35);
        for (var despesa : despesas) {
            modelo.addRow(new Object[]{despesa.getData().format(DateTimeFormatter.ofPattern("dd/MM/yyyy")),
                                        despesa.getTipoTransacao().getDescricao(),
                                        String.format("R$ %.2f", despesa.getValor())});
        }
    }//GEN-LAST:event_btConsultarDespesasActionPerformed

    // 7) Listar todos os lançamentos (receitas e despesas) ordenados por data. A cada lançamento, exibir como aquele
    // lançamento impactou no saldo. Isto é, totalizar o saldo até aquele momento, assim como ocorre num extrato;
    private void btConsultarLancamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultarLancamentosActionPerformed
        LinkedList<Transacao> transacoes = new LinkedList<>();
        try {
            transacoes = ManipuladorArquivo.lerArquivo();
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
        Collections.sort(transacoes, Comparator.comparing(Transacao::getData));
        
        DefaultTableModel modelo = (DefaultTableModel) tbConsultarLancamentos.getModel();
        modelo.setRowCount(0);
        var modeloColuna = tbConsultarLancamentos.getColumnModel();
        modeloColuna.getColumn(0).setPreferredWidth(25);
        modeloColuna.getColumn(1).setPreferredWidth(25);
        modeloColuna.getColumn(2).setPreferredWidth(100);
        modeloColuna.getColumn(3).setPreferredWidth(35);
        modeloColuna.getColumn(4).setPreferredWidth(35);

        double saldo = 0;
        for (var transacao : transacoes) {
            var valorTransacao = transacao.getValor();
            if (transacao.getCategoria() == CategoriaTransacao.DESPESA) {
                saldo -= valorTransacao;
            } else {
                saldo += valorTransacao;
            }
            modelo.addRow(new Object[]{transacao.getData().format(DateTimeFormatter.ofPattern("dd/MM/yyyy")),
                                        transacao.getCategoria().toString(),
                                        transacao.getTipoTransacao().getDescricao(),
                                        String.format("R$ %.2f", transacao.getValor()),
                                        String.format("R$ %.2f", saldo)
            });
        }
    }//GEN-LAST:event_btConsultarLancamentosActionPerformed

    // 1) Incluir receitas. Uma receita deve ser categorizável e deve ser possível informar a data em que a receita ocorreu (ou vai ocorrer);
    private void btIncluirReceitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIncluirReceitaActionPerformed
        var valorFormatado = tfValorDaReceita.getText().replace(',', '.');
        var dataStr = tfDataReceita.getText();
        var cadastrado = cadastrarTransacao(valorFormatado, dataStr, cbTipoDeReceita.getSelectedItem().toString(), CategoriaTransacao.RECEITA);
        if (cadastrado) {
            JOptionPane.showMessageDialog(rootPane, "Receita cadastrada com sucesso!");
        }
    }//GEN-LAST:event_btIncluirReceitaActionPerformed

    // 2) Incluir despesas. Uma despesa deve ser categorizável. Deve ser possível informar a data em que a despesa ocorreu (ou vai ocorrer);
    private void btIncluirDespesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIncluirDespesaActionPerformed
        var valorFormatado = tfValorDaDespesa.getText().replace(',', '.');
        var dataStr = tfDataDespesa.getText();
        var cadastrado = cadastrarTransacao(valorFormatado, dataStr, cbTipoDeDespesa.getSelectedItem().toString(), CategoriaTransacao.DESPESA);
        if (cadastrado) {
            JOptionPane.showMessageDialog(rootPane, "Despesa cadastrada com sucesso!");
        }
    }//GEN-LAST:event_btIncluirDespesaActionPerformed

    private void btConsultarSaldoIndependenteDaDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultarSaldoIndependenteDaDataActionPerformed
        try {
            var saldo = ControleSaldo.calcularTotalSaldo();
            lbConsultaSaldoIndependenteDoPeriodo.setText(String.format("R$ %.2f", saldo));
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btConsultarSaldoIndependenteDaDataActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new App().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelConsultaDeSaldo;
    private javax.swing.JPanel PanelConsultaDespesa;
    private javax.swing.JPanel PanelConsultaReceita;
    private javax.swing.JPanel PanelConsultarLancamentos;
    private javax.swing.JPanel PanelIncluirDespesa;
    private javax.swing.JPanel PanelIncluirReceita;
    private javax.swing.JButton btConsultarDespesas;
    private javax.swing.JButton btConsultarLancamentos;
    private javax.swing.JButton btConsultarReceitas;
    private javax.swing.JButton btConsultarSaldoAtual;
    private javax.swing.JButton btConsultarSaldoIndependenteDaData;
    private javax.swing.JButton btIncluirDespesa;
    private javax.swing.JButton btIncluirReceita;
    private javax.swing.JComboBox<String> cbTipoDeDespesa;
    private javax.swing.JComboBox<String> cbTipoDeDespesaConsulta;
    private javax.swing.JComboBox<String> cbTipoDeReceita;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lbConsultaSaldoDataAtual;
    private javax.swing.JLabel lbConsultaSaldoIndependenteDoPeriodo;
    private javax.swing.JLabel lblDataDespesa;
    private javax.swing.JLabel lblDataReceita;
    private javax.swing.JTable tbConsultarDespesaFiltrada;
    private javax.swing.JTable tbConsultarLancamentos;
    private javax.swing.JTable tbConsultarReceita;
    private javax.swing.JTextField tfDataDespesa;
    private javax.swing.JTextField tfDataReceita;
    private javax.swing.JTextField tfValorDaDespesa;
    private javax.swing.JTextField tfValorDaReceita;
    // End of variables declaration//GEN-END:variables
}
