/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.math.BigDecimal;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import model.TipoTransacao;
import model.ControleSaldo;
import model.Despesa;
import model.ManipuladorArquivo;
import model.Receita;
import model.TipoReceita;
import model.CategoriaTransacao;
import model.Transacao;

/**
 *
 * @author crist
 */
public class App extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public App() {
        initComponents();
    }
    
    private static boolean validarValorValido(String valorStr) {
        try {
            Double.parseDouble(valorStr);
            return true;
        } catch (NumberFormatException e) {
            return false;
        }
    }
    
    private static boolean validarDataValida(String dataStr) {
        String regex = "^(0[1-9]|[12][0-9]|3[01])/(0[1-9]|1[0-2])/\\d{4}$";
        Pattern pattern = Pattern.compile(regex);
        Matcher matcher = pattern.matcher(dataStr);

        return matcher.matches();
    }
    
    private static LocalDate transformarStringData(String dataStr) {
        DateTimeFormatter formato = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        LocalDate data;
        data = LocalDate.parse(dataStr, formato);
        
        return data;
    }
    
    private boolean cadastrarTransacao(String valorFormatado, String dataTransacao, String descricaoTipo, CategoriaTransacao tipoTransacao) {
        var informacoesInvalidas = false;
        if (valorFormatado.isBlank()) {
            JOptionPane.showMessageDialog(rootPane, "É necessário informar um valor para cadastrar a transação!", "Aviso", JOptionPane.WARNING_MESSAGE);
            informacoesInvalidas = true;
        }
        if (dataTransacao.isBlank()) {
            JOptionPane.showMessageDialog(rootPane, "É necessário informar uma data para cadastrar a transação!", "Aviso", JOptionPane.WARNING_MESSAGE);
            informacoesInvalidas = true;
        }
        if (informacoesInvalidas) {
            return false;
        }
        if (!validarValorValido(valorFormatado)) {
            JOptionPane.showMessageDialog(rootPane, "O valor está em um formato inválido!", "Erro", JOptionPane.ERROR_MESSAGE);
            informacoesInvalidas = true;
        }
        if (!validarDataValida(dataTransacao)) {
            JOptionPane.showMessageDialog(rootPane, "A data está em um formato inválido!", "Erro", JOptionPane.ERROR_MESSAGE);
            informacoesInvalidas = true;
        }
        if (informacoesInvalidas) {
            return false;
        }
        
        var data = transformarStringData(dataTransacao);
        var categoria = TipoTransacao.getTipoTransacaoPorDescricao(descricaoTipo);
        Transacao transacao;
        
        if (tipoTransacao == CategoriaTransacao.DESPESA) {
            transacao = new Despesa(Double.parseDouble(valorFormatado), categoria, data);
        } else {
            transacao = new Receita(Double.parseDouble(valorFormatado), categoria, data);
        }

        // salvar no arquivo        
        ManipuladorArquivo.incluirTransacao(transacao);
        
        return true;
    }
        
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelIncluirDespesa = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tfValorDaDespesa = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cbTipoDeDespesa = new javax.swing.JComboBox<>();
        btIncluirDespesa = new javax.swing.JButton();
        lblDataDespesa = new javax.swing.JLabel();
        tfDataDespesa = new javax.swing.JTextField();
        PanelIncluirReceita = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        tfValorDaReceita = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cbTipoDeReceita = new javax.swing.JComboBox<>();
        btIncluirReceita = new javax.swing.JButton();
        lblDataReceita = new javax.swing.JLabel();
        tfDataReceita = new javax.swing.JTextField();
        PanelConsultaDeSaldo = new javax.swing.JPanel();
        btConsultarSaldoAtual = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btConsultarSaldoIndependenteDaData = new javax.swing.JButton();
        lbConsultaSaldoDataAtual = new javax.swing.JLabel();
        lbConsultaSaldoIndependenteDoPeriodo = new javax.swing.JLabel();
        PanelConsultaReceita = new javax.swing.JPanel();
        btConsultarReceitas = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        taConsultarReceita = new javax.swing.JTextArea();
        PanelConsultaDespesa = new javax.swing.JPanel();
        cbTipoDeDespesaConsulta = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        btConsultarDespesas = new javax.swing.JButton();
        lbConsultarDespesas = new javax.swing.JLabel();
        PanelConsultarLancamentos = new javax.swing.JPanel();
        lbConsultaDeLançamentos = new javax.swing.JLabel();
        btConsultarLancamentos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelIncluirDespesa.setBorder(javax.swing.BorderFactory.createTitledBorder("Incluir Despesa"));

        jLabel2.setText("Valor da Despesa: ");

        tfValorDaDespesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfValorDaDespesaActionPerformed(evt);
            }
        });

        jLabel3.setText("Tipo da Despesa");

        cbTipoDeDespesa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alimentação", "Transporte", "Residência", "Saúde", "Educação", "Entretenimento", "Outras" }));
        cbTipoDeDespesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTipoDeDespesaActionPerformed(evt);
            }
        });

        btIncluirDespesa.setText("Inlcuir Despesa");
        btIncluirDespesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIncluirDespesaActionPerformed(evt);
            }
        });

        lblDataDespesa.setText("Data da Despesa: ");

        tfDataDespesa.setToolTipText("Data no formato dia/mês/ano");
        tfDataDespesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDataDespesaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelIncluirDespesaLayout = new javax.swing.GroupLayout(PanelIncluirDespesa);
        PanelIncluirDespesa.setLayout(PanelIncluirDespesaLayout);
        PanelIncluirDespesaLayout.setHorizontalGroup(
            PanelIncluirDespesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelIncluirDespesaLayout.createSequentialGroup()
                .addGroup(PanelIncluirDespesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelIncluirDespesaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(PanelIncluirDespesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelIncluirDespesaLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(cbTipoDeDespesa, 0, 193, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelIncluirDespesaLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btIncluirDespesa)
                                .addGap(86, 86, 86))))
                    .addGroup(PanelIncluirDespesaLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(PanelIncluirDespesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(lblDataDespesa))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelIncluirDespesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfValorDaDespesa, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                            .addComponent(tfDataDespesa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE))))
                .addContainerGap())
        );
        PanelIncluirDespesaLayout.setVerticalGroup(
            PanelIncluirDespesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelIncluirDespesaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelIncluirDespesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfValorDaDespesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelIncluirDespesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDataDespesa)
                    .addComponent(tfDataDespesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelIncluirDespesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbTipoDeDespesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btIncluirDespesa)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PanelIncluirReceita.setBorder(javax.swing.BorderFactory.createTitledBorder("Incluir Receita"));

        jLabel4.setText("Valor da Receita");

        tfValorDaReceita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfValorDaReceitaActionPerformed(evt);
            }
        });

        jLabel5.setText("Tipo de Receita:");

        cbTipoDeReceita.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Recebimento de Salário", "Décimo Terceiro", "Férias", "Outras" }));
        cbTipoDeReceita.setToolTipText("");
        cbTipoDeReceita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTipoDeReceitaActionPerformed(evt);
            }
        });

        btIncluirReceita.setText("Inlcuir Receita");
        btIncluirReceita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIncluirReceitaActionPerformed(evt);
            }
        });

        lblDataReceita.setText("Data da Receita: ");

        tfDataReceita.setToolTipText("Data no formato dia/mês/ano");
        tfDataReceita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDataReceitaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelIncluirReceitaLayout = new javax.swing.GroupLayout(PanelIncluirReceita);
        PanelIncluirReceita.setLayout(PanelIncluirReceitaLayout);
        PanelIncluirReceitaLayout.setHorizontalGroup(
            PanelIncluirReceitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelIncluirReceitaLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(PanelIncluirReceitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(lblDataReceita))
                .addGap(18, 18, 18)
                .addGroup(PanelIncluirReceitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfDataReceita, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfValorDaReceita, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
            .addGroup(PanelIncluirReceitaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(PanelIncluirReceitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelIncluirReceitaLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(btIncluirReceita))
                    .addComponent(cbTipoDeReceita, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        PanelIncluirReceitaLayout.setVerticalGroup(
            PanelIncluirReceitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelIncluirReceitaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelIncluirReceitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfValorDaReceita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelIncluirReceitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDataReceita)
                    .addComponent(tfDataReceita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelIncluirReceitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cbTipoDeReceita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btIncluirReceita)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PanelConsultaDeSaldo.setBorder(javax.swing.BorderFactory.createTitledBorder("Consulta de Saldo"));

        btConsultarSaldoAtual.setText("Consultar");
        btConsultarSaldoAtual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultarSaldoAtualActionPerformed(evt);
            }
        });

        jLabel1.setText("Consultar saldo até a data atual:");

        jLabel6.setText("Consultar saldo independente do período:");

        btConsultarSaldoIndependenteDaData.setText("Consultar");
        btConsultarSaldoIndependenteDaData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultarSaldoIndependenteDaDataActionPerformed(evt);
            }
        });

        lbConsultaSaldoDataAtual.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbConsultaSaldoIndependenteDoPeriodo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout PanelConsultaDeSaldoLayout = new javax.swing.GroupLayout(PanelConsultaDeSaldo);
        PanelConsultaDeSaldo.setLayout(PanelConsultaDeSaldoLayout);
        PanelConsultaDeSaldoLayout.setHorizontalGroup(
            PanelConsultaDeSaldoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelConsultaDeSaldoLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(PanelConsultaDeSaldoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelConsultaDeSaldoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbConsultaSaldoDataAtual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbConsultaSaldoIndependenteDoPeriodo, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelConsultaDeSaldoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btConsultarSaldoIndependenteDaData, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btConsultarSaldoAtual, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        PanelConsultaDeSaldoLayout.setVerticalGroup(
            PanelConsultaDeSaldoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelConsultaDeSaldoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelConsultaDeSaldoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbConsultaSaldoDataAtual, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(PanelConsultaDeSaldoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(btConsultarSaldoAtual)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelConsultaDeSaldoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(PanelConsultaDeSaldoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btConsultarSaldoIndependenteDaData))
                    .addComponent(lbConsultaSaldoIndependenteDoPeriodo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        PanelConsultaReceita.setBorder(javax.swing.BorderFactory.createTitledBorder("Consulta de Receitas"));

        btConsultarReceitas.setText("Consultar Receitas");
        btConsultarReceitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultarReceitasActionPerformed(evt);
            }
        });

        taConsultarReceita.setEditable(false);
        taConsultarReceita.setColumns(20);
        taConsultarReceita.setRows(5);
        jScrollPane1.setViewportView(taConsultarReceita);

        javax.swing.GroupLayout PanelConsultaReceitaLayout = new javax.swing.GroupLayout(PanelConsultaReceita);
        PanelConsultaReceita.setLayout(PanelConsultaReceitaLayout);
        PanelConsultaReceitaLayout.setHorizontalGroup(
            PanelConsultaReceitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelConsultaReceitaLayout.createSequentialGroup()
                .addGroup(PanelConsultaReceitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelConsultaReceitaLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(btConsultarReceitas))
                    .addGroup(PanelConsultaReceitaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelConsultaReceitaLayout.setVerticalGroup(
            PanelConsultaReceitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelConsultaReceitaLayout.createSequentialGroup()
                .addComponent(btConsultarReceitas)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        PanelConsultaDespesa.setBorder(javax.swing.BorderFactory.createTitledBorder("Consulta de Despesa"));

        cbTipoDeDespesaConsulta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Alimentação", "Transporte", "Residência", "Saúde", "Educação", "Entretenimento", "Outras Despesas" }));
        cbTipoDeDespesaConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTipoDeDespesaConsultaActionPerformed(evt);
            }
        });

        jLabel8.setText("Tipo de despesa:");

        btConsultarDespesas.setText("Consultar Despesas");
        btConsultarDespesas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultarDespesasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelConsultaDespesaLayout = new javax.swing.GroupLayout(PanelConsultaDespesa);
        PanelConsultaDespesa.setLayout(PanelConsultaDespesaLayout);
        PanelConsultaDespesaLayout.setHorizontalGroup(
            PanelConsultaDespesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelConsultaDespesaLayout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelConsultaDespesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btConsultarDespesas, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                    .addComponent(cbTipoDeDespesaConsulta, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelConsultaDespesaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbConsultarDespesas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        PanelConsultaDespesaLayout.setVerticalGroup(
            PanelConsultaDespesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelConsultaDespesaLayout.createSequentialGroup()
                .addGroup(PanelConsultaDespesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cbTipoDeDespesaConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btConsultarDespesas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbConsultarDespesas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        PanelConsultarLancamentos.setBorder(javax.swing.BorderFactory.createTitledBorder("Consulta de Lançamentos"));

        btConsultarLancamentos.setText("Consultar Lançamentos");
        btConsultarLancamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultarLancamentosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelConsultarLancamentosLayout = new javax.swing.GroupLayout(PanelConsultarLancamentos);
        PanelConsultarLancamentos.setLayout(PanelConsultarLancamentosLayout);
        PanelConsultarLancamentosLayout.setHorizontalGroup(
            PanelConsultarLancamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelConsultarLancamentosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbConsultaDeLançamentos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(PanelConsultarLancamentosLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(btConsultarLancamentos)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        PanelConsultarLancamentosLayout.setVerticalGroup(
            PanelConsultarLancamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelConsultarLancamentosLayout.createSequentialGroup()
                .addComponent(btConsultarLancamentos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbConsultaDeLançamentos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(PanelConsultaReceita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(PanelConsultaDespesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(PanelConsultarLancamentos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(84, 84, 84)
                                .addComponent(PanelIncluirReceita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(76, 76, 76)
                                .addComponent(PanelIncluirDespesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(217, 217, 217)
                                .addComponent(PanelConsultaDeSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelIncluirReceita, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelIncluirDespesa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PanelConsultaDespesa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelConsultaReceita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PanelConsultarLancamentos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelConsultaDeSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfValorDaDespesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfValorDaDespesaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfValorDaDespesaActionPerformed

    private void cbTipoDeDespesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTipoDeDespesaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTipoDeDespesaActionPerformed

    private void tfValorDaReceitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfValorDaReceitaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfValorDaReceitaActionPerformed

    private void cbTipoDeReceitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTipoDeReceitaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTipoDeReceitaActionPerformed

    private void btConsultarSaldoAtualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultarSaldoAtualActionPerformed
        // TODO add your handling code here:
        var saldo = ControleSaldo.calcularSaldoAteDataAtual();
        lbConsultaSaldoDataAtual.setText(String.format("R$ %.2f", saldo));
    }//GEN-LAST:event_btConsultarSaldoAtualActionPerformed

    private void btConsultarReceitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultarReceitasActionPerformed
        // TODO add your handling code here:
        var receitas = ControleSaldo.retornaTransacoesDeReceita();
        String lista = "DATA -------------- TIPO TRANSAÇÃO ------------ VALOR\n";
        for (var receita : receitas) {
            lista += String.format("\n%s    %s    R$ %.2f", receita.getData().format(DateTimeFormatter.ofPattern("dd/MM/yyyy")), receita.getTipoTransacao().getDescricao(), receita.getValor());
        }
        taConsultarReceita.setText(lista);
    }//GEN-LAST:event_btConsultarReceitasActionPerformed

    private void cbTipoDeDespesaConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTipoDeDespesaConsultaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTipoDeDespesaConsultaActionPerformed

    private void btConsultarDespesasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultarDespesasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btConsultarDespesasActionPerformed

    private void btConsultarLancamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultarLancamentosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btConsultarLancamentosActionPerformed

    private void btIncluirReceitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIncluirReceitaActionPerformed
        // inclusão de receita
        var valorFormatado = tfValorDaReceita.getText().replace(',', '.');
        var dataStr = tfDataReceita.getText();
        var cadastrado = cadastrarTransacao(valorFormatado, dataStr, cbTipoDeReceita.getSelectedItem().toString(), CategoriaTransacao.RECEITA);
        if (cadastrado) {
            JOptionPane.showMessageDialog(rootPane, "Receita cadastrada com sucesso!");
        }
    }//GEN-LAST:event_btIncluirReceitaActionPerformed

    private void btIncluirDespesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIncluirDespesaActionPerformed
        // inclusão de despesa
        var valorFormatado = tfValorDaDespesa.getText().replace(',', '.');
        var dataStr = tfDataDespesa.getText();
        var cadastrado = cadastrarTransacao(valorFormatado, dataStr, cbTipoDeDespesa.getSelectedItem().toString(), CategoriaTransacao.DESPESA);
        if (cadastrado) {
            JOptionPane.showMessageDialog(rootPane, "Despesa cadastrada com sucesso!");
        }
    }//GEN-LAST:event_btIncluirDespesaActionPerformed

    private void tfDataDespesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDataDespesaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfDataDespesaActionPerformed

    private void tfDataReceitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDataReceitaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfDataReceitaActionPerformed

    private void btConsultarSaldoIndependenteDaDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultarSaldoIndependenteDaDataActionPerformed
        // TODO add your handling code here:
        var saldo = ControleSaldo.calcularTotalSaldo();
        lbConsultaSaldoIndependenteDoPeriodo.setText(String.format("R$ %.2f", saldo));
    }//GEN-LAST:event_btConsultarSaldoIndependenteDaDataActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new App().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelConsultaDeSaldo;
    private javax.swing.JPanel PanelConsultaDespesa;
    private javax.swing.JPanel PanelConsultaReceita;
    private javax.swing.JPanel PanelConsultarLancamentos;
    private javax.swing.JPanel PanelIncluirDespesa;
    private javax.swing.JPanel PanelIncluirReceita;
    private javax.swing.JButton btConsultarDespesas;
    private javax.swing.JButton btConsultarLancamentos;
    private javax.swing.JButton btConsultarReceitas;
    private javax.swing.JButton btConsultarSaldoAtual;
    private javax.swing.JButton btConsultarSaldoIndependenteDaData;
    private javax.swing.JButton btIncluirDespesa;
    private javax.swing.JButton btIncluirReceita;
    private javax.swing.JComboBox<String> cbTipoDeDespesa;
    private javax.swing.JComboBox<String> cbTipoDeDespesaConsulta;
    private javax.swing.JComboBox<String> cbTipoDeReceita;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbConsultaDeLançamentos;
    private javax.swing.JLabel lbConsultaSaldoDataAtual;
    private javax.swing.JLabel lbConsultaSaldoIndependenteDoPeriodo;
    private javax.swing.JLabel lbConsultarDespesas;
    private javax.swing.JLabel lblDataDespesa;
    private javax.swing.JLabel lblDataReceita;
    private javax.swing.JTextArea taConsultarReceita;
    private javax.swing.JTextField tfDataDespesa;
    private javax.swing.JTextField tfDataReceita;
    private javax.swing.JTextField tfValorDaDespesa;
    private javax.swing.JTextField tfValorDaReceita;
    // End of variables declaration//GEN-END:variables
}
